version: '3.8'

services:

  reverse_proxy:
    image: nginx
    container_name: reverse_proxy
    restart: unless-stopped
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:80"
    depends_on:
      - api_1
      - api_2

  api_1:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    env_file:
      - .env
    command: fastapi dev main.py --host 0.0.0.0 --port 80

  api_2:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    env_file:
      - .env
    command: fastapi dev main.py --host 0.0.0.0 --port 80
